"""Gate Client SDK ergonomic Python interface to the Gate LLM Gateway."""

from gate_common.models.audio import AudioRequest, AudioResponse
from gate_common.models.audio_gen import AudioGenMode, AudioGenRequest, AudioGenResponse, AudioMode, DialogueTurn
from gate_common.models.audio_isolation import AudioIsolationRequest, AudioIsolationResponse
from gate_common.models.config import (
    DeploymentInfo,
    DeploymentStatus,
    ExtraAttributeName,
    ModelCapabilities,
    ModelInfo,
    ModelPurpose,
    ResolvedDeployment,
    ResolveResponse,
)
from gate_common.models.dubbing import DubbingRequest, DubbingResponse
from gate_common.models.embed import EmbedObject, EmbedRequest, EmbedResponse
from gate_common.models.images import ImageData, ImageRequest, ImageResponse
from gate_common.models.messages import ImageMessage, Message, MessageRole, TextMessage
from gate_common.models.request import BestTarget, CallControl, RequestSpecifics, ResolveRequest, ZoneSelection
from gate_common.models.response import (
    BaseAudioResponse,
    GateCallRecord,
    GateResponse,
    MulticallStreamFrame,
    RawUsage,
    StreamChunk,
    ToolCall,
    ToolFunction,
    VisionGateResponse,
)
from gate_common.models.responses import ResponsesRequest, ResponsesResponse
from gate_common.models.tts import TTSRequest, TTSResponse
from gate_common.models.video import VideoRequest, VideoResponse
from gate_common.models.vision import VisionLine, VisionOCR, VisionOCRRequest, VisionPoint, VisionWord
from gate_common.types import JsonDict, JsonValue, OutputStatus, ReasoningEffort

from .client import GateClient
from .exceptions import (
    GateAuthError,
    GateBudgetError,
    GateCapabilityError,
    GateConnectionError,
    GateError,
    GateEscapeHatchWarning,
    GateModelNotFoundError,
    GateServerError,
    GateTimeoutError,
)
from .request import (
    AudioCallback,
    AudioGenRequestBuilder,
    BudgetCheck,
    DirectRequestBuilder,
    GateCallback,
    ImageCallback,
    ImageRequestBuilder,
    JsonGateResponse,
    JsonRequestBuilder,
    MediaBuilder,
    OnUsage,
    StreamingToolExecutor,
    ToolExecutor,
    ToolProgress,
    ToolResult,
    ToolStreamItem,
    TTSRequestBuilder,
    TypedGateResponse,
    UsageCallback,
    VideoCallback,
    VideoRequestBuilder,
    select_best,
)
from .tokens import count, estimate_input_tokens

__all__ = [
    "AudioCallback",
    "AudioGenMode",
    "AudioGenRequest",
    "AudioGenRequestBuilder",
    "AudioGenResponse",
    "AudioIsolationRequest",
    "AudioIsolationResponse",
    "AudioMode",
    "AudioRequest",
    "AudioResponse",
    "BaseAudioResponse",
    "BestTarget",
    "BudgetCheck",
    "CallControl",
    "DeploymentInfo",
    "DeploymentStatus",
    "DialogueTurn",
    "DirectRequestBuilder",
    "DubbingRequest",
    "DubbingResponse",
    "EmbedObject",
    "EmbedRequest",
    "EmbedResponse",
    "ExtraAttributeName",
    "GateAuthError",
    "GateBudgetError",
    "GateCallRecord",
    "GateCallback",
    "GateCapabilityError",
    "GateClient",
    "GateConnectionError",
    "GateError",
    "GateEscapeHatchWarning",
    "GateModelNotFoundError",
    "GateResponse",
    "GateServerError",
    "GateTimeoutError",
    "ImageCallback",
    "ImageData",
    "ImageMessage",
    "ImageRequest",
    "ImageRequestBuilder",
    "ImageResponse",
    "JsonDict",
    "JsonGateResponse",
    "JsonRequestBuilder",
    "JsonValue",
    "MediaBuilder",
    "Message",
    "MessageRole",
    "ModelCapabilities",
    "ModelInfo",
    "ModelPurpose",
    "MulticallStreamFrame",
    "OnUsage",
    "OutputStatus",
    "RawUsage",
    "ReasoningEffort",
    "RequestSpecifics",
    "ResolveRequest",
    "ResolveResponse",
    "ResolvedDeployment",
    "ResponsesRequest",
    "ResponsesResponse",
    "StreamChunk",
    "StreamingToolExecutor",
    "TTSRequest",
    "TTSRequestBuilder",
    "TTSResponse",
    "TextMessage",
    "ToolCall",
    "ToolExecutor",
    "ToolFunction",
    "ToolProgress",
    "ToolResult",
    "ToolStreamItem",
    "TypedGateResponse",
    "UsageCallback",
    "VideoCallback",
    "VideoRequest",
    "VideoRequestBuilder",
    "VideoResponse",
    "VisionGateResponse",
    "VisionLine",
    "VisionOCR",
    "VisionOCRRequest",
    "VisionPoint",
    "VisionWord",
    "ZoneSelection",
    "count",
    "estimate_input_tokens",
    "select_best",
]
